/*
 *    This file is part of ReadonlyREST.
 *
 *    ReadonlyREST is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    ReadonlyREST is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with ReadonlyREST.  If not, see http://www.gnu.org/licenses/
 */
package tech.beshu.ror.accesscontrol.matchers

import tech.beshu.ror.accesscontrol.domain.Action
import tech.beshu.ror.accesscontrol.domain.Action.RorAction

// todo: audit - admin, admin in field USR

// Action strings sourced from ES 9.2.3:
// https://github.com/beshu-tech/readonlyrest-docs/blob/master/actionstrings/action_strings_es9.2.3.txt
object ActionMatchers {

  val readNonClusterManagementActionPatternsMatcher: PatternsMatcher[Action] = PatternsMatcher.create {
    RorAction.readOnlyActions ++ Set(
      // indices:admin read actions
      "indices:admin/aliases/get",
      "indices:admin/analyze",
      "indices:admin/analyze_disk_usage",
      "indices:admin/data_stream/get",
      "indices:admin/data_stream/lifecycle/explain",
      "indices:admin/data_stream/lifecycle/get",
      "indices:admin/data_stream/options/get",
      "indices:admin/get",
      "indices:admin/ilm/explain",
      "indices:admin/index_template/get",
      "indices:admin/index_template/simulate",
      "indices:admin/index_template/simulate_index",
      "indices:admin/inference/fields/get",
      "indices:admin/mappings/fields/get",
      "indices:admin/mappings/get",
      "indices:admin/migration/reindex_status",
      "indices:admin/refresh",
      "indices:admin/refresh/unpromotable",
      "indices:admin/resolve/cluster",
      "indices:admin/resolve/index",
      "indices:admin/sample",
      "indices:admin/sample/stats",
      "indices:admin/search/search_shards",
      "indices:admin/shards/search_shards",
      "indices:admin/template/get",
      "indices:admin/validate/query",
      // indices:data/read actions
      "indices:data/read/async_search/get",
      "indices:data/read/async_search/submit",
      "indices:data/read/close_point_in_time",
      "indices:data/read/downsample_delegate",
      "indices:data/read/eql",
      "indices:data/read/eql/async/get",
      "indices:data/read/esql",
      "indices:data/read/esql/async/get",
      "indices:data/read/esql/async/stop",
      "indices:data/read/esql/compute",
      "indices:data/read/esql/resolve_fields",
      "indices:data/read/esql/search_shards",
      "indices:data/read/explain",
      "indices:data/read/field_caps",
      "indices:data/read/get",
      "indices:data/read/get_from_translog",
      "indices:data/read/mget",
      "indices:data/read/msearch",
      "indices:data/read/mtv",
      "indices:data/read/open_point_in_time",
      "indices:data/read/open_reader_context",
      "indices:data/read/profiling/flamegraph",
      "indices:data/read/profiling/stack_traces",
      "indices:data/read/profiling/topn/functions",
      "indices:data/read/rank_eval",
      "indices:data/read/scroll",
      "indices:data/read/scroll/clear",
      "indices:data/read/search",
      "indices:data/read/search[can_match][n]",
      "indices:data/read/search[clear_scroll_contexts]",
      "indices:data/read/search[free_context/scroll]",
      "indices:data/read/search[free_context]",
      "indices:data/read/search[phase/dfs]",
      "indices:data/read/search[phase/fetch/id/scroll]",
      "indices:data/read/search[phase/fetch/id]",
      "indices:data/read/search[phase/query+fetch/scroll]",
      "indices:data/read/search[phase/query/id]",
      "indices:data/read/search[phase/query/scroll]",
      "indices:data/read/search[phase/query]",
      "indices:data/read/search[phase/rank/feature]",
      "indices:data/read/search[query][n]",
      "indices:data/read/search/template",
      "indices:data/read/sql",
      "indices:data/read/sql/async/get",
      "indices:data/read/sql/close_cursor",
      "indices:data/read/sql/translate",
      "indices:data/read/tv",
      "indices:data/read/xpack/application/search_application/search",
      "indices:data/read/xpack/ccr/shard_changes",
      "indices:data/read/xpack/enrich/coordinate_lookups",
      "indices:data/read/xpack/graph/explore",
      "indices:data/read/xpack/rollup/get/index/caps",
      "indices:data/read/xpack/rollup/search",
      "indices:data/read/xpack/termsenum/list",
      // indices:monitor actions
      "indices:monitor/data_stream/mappings/get",
      "indices:monitor/data_stream/settings/get",
      "indices:monitor/data_stream/stats",
      "indices:monitor/field_usage_stats",
      "indices:monitor/fleet/global_checkpoints",
      "indices:monitor/fleet/global_checkpoints[s]",
      "indices:monitor/recovery",
      "indices:monitor/sample/config/get",
      "indices:monitor/sample/config/get_all",
      "indices:monitor/segments",
      "indices:monitor/settings/get",
      "indices:monitor/shard_stores",
      "indices:monitor/stats",
      "indices:monitor/transform/checkpoint",
      // cluster:admin/xpack read actions
      "cluster:admin/xpack/application/analytics/get",
      "cluster:admin/xpack/application/search_application/get",
      "cluster:admin/xpack/application/search_application/list",
      "cluster:admin/xpack/application/search_application/render_query",
      "cluster:admin/xpack/ccr/auto_follow_pattern/get",
      "cluster:admin/xpack/ccr/auto_follow_pattern/resolve",
      "cluster:admin/xpack/connector/get",
      "cluster:admin/xpack/connector/list",
      "cluster:admin/xpack/connector/secret/get",
      "cluster:admin/xpack/connector/sync_job/get",
      "cluster:admin/xpack/connector/sync_job/list",
      "cluster:admin/xpack/deprecation/info",
      "cluster:admin/xpack/deprecation/nodes/info",
      "cluster:admin/xpack/enrich/get",
      "cluster:admin/xpack/esql/view/get",
      "cluster:admin/xpack/license/basic_status",
      "cluster:admin/xpack/license/feature_usage",
      "cluster:admin/xpack/license/trial_status",
      "cluster:admin/xpack/ml/data_frame/analytics/explain",
      "cluster:admin/xpack/ml/data_frame/analytics/preview",
      "cluster:admin/xpack/ml/datafeeds/preview",
      "cluster:admin/xpack/ml/filters/get",
      "cluster:admin/xpack/ml/job/estimate_model_memory",
      "cluster:admin/xpack/ml/job/validate",
      "cluster:admin/xpack/ml/job/validate/detector",
      "cluster:admin/xpack/query_rules/get",
      "cluster:admin/xpack/query_rules/list",
      "cluster:admin/xpack/query_rules/rule/get",
      "cluster:admin/xpack/searchable_snapshots/cache/stats",
      "cluster:admin/xpack/security/api_key/get",
      "cluster:admin/xpack/security/api_key/query",
      "cluster:admin/xpack/security/privilege/builtin/get",
      "cluster:admin/xpack/security/privilege/get",
      "cluster:admin/xpack/security/profile/get",
      "cluster:admin/xpack/security/profile/has_privileges",
      "cluster:admin/xpack/security/profile/suggest",
      "cluster:admin/xpack/security/role/get",
      "cluster:admin/xpack/security/role/query",
      "cluster:admin/xpack/security/role_mapping/get",
      "cluster:admin/xpack/security/service_account/credential/get",
      "cluster:admin/xpack/security/service_account/get",
      "cluster:admin/xpack/security/user/authenticate",
      "cluster:admin/xpack/security/user/get",
      "cluster:admin/xpack/security/user/has_privileges",
      "cluster:admin/xpack/security/user/list_privileges",
      "cluster:admin/xpack/security/user/query",
      "cluster:admin/xpack/watcher/settings/get",
    ).map(Action.apply) ++
      Set(
        // cluster:monitor actions
        "cluster:monitor/allocation/explain",
        "cluster:monitor/allocation/stats",
        "cluster:monitor/async_search/status",
        "cluster:monitor/ccr/follow_info",
        "cluster:monitor/ccr/follow_stats",
        "cluster:monitor/ccr/stats",
        "cluster:monitor/data_stream/lifecycle/stats",
        "cluster:monitor/eql/async/status",
        "cluster:monitor/fetch/health/info",
        "cluster:monitor/health",
        "cluster:monitor/health_api",
        "cluster:monitor/health_api/stats",
        "cluster:monitor/ingest/geoip/stats",
        "cluster:monitor/main",
        "cluster:monitor/nodes/capabilities",
        "cluster:monitor/nodes/data_tier_usage",
        "cluster:monitor/nodes/features",
        "cluster:monitor/nodes/hot_threads",
        "cluster:monitor/nodes/info",
        "cluster:monitor/nodes/stats",
        "cluster:monitor/nodes/usage",
        "cluster:monitor/profiling/status/get",
        "cluster:monitor/remote/info",
        "cluster:monitor/settings",
        "cluster:monitor/state",
        "cluster:monitor/stats",
        "cluster:monitor/stats/remote",
        "cluster:monitor/task",
        "cluster:monitor/task/get",
        "cluster:monitor/tasks/lists",
        "cluster:monitor/text_structure/find_field_structure",
        "cluster:monitor/text_structure/find_message_structure",
        "cluster:monitor/text_structure/findstructure",
        "cluster:monitor/text_structure/test_grok_pattern",
        "cluster:monitor/transform/get",
        "cluster:monitor/transform/stats/get",
        "cluster:monitor/update/health/info",
        "cluster:monitor/xpack/analytics/stats",
        "cluster:monitor/xpack/enrich/coordinator_stats",
        "cluster:monitor/xpack/enrich/stats",
        "cluster:monitor/xpack/eql/stats/dist",
        "cluster:monitor/xpack/esql/get_query",
        "cluster:monitor/xpack/esql/list_queries",
        "cluster:monitor/xpack/esql/stats/dist",
        "cluster:monitor/xpack/gpu_vector_indexing/stats/dist",
        "cluster:monitor/xpack/inference/ccm/get",
        "cluster:monitor/xpack/inference/diagnostics/get",
        "cluster:monitor/xpack/inference/get",
        "cluster:monitor/xpack/inference/post",
        "cluster:monitor/xpack/inference/services/get",
        "cluster:monitor/xpack/info",
        "cluster:monitor/xpack/license/get",
        "cluster:monitor/xpack/ml/autoscaling/stats/get",
        "cluster:monitor/xpack/ml/calendars/events/get",
        "cluster:monitor/xpack/ml/calendars/get",
        "cluster:monitor/xpack/ml/data_frame/analytics/get",
        "cluster:monitor/xpack/ml/data_frame/analytics/stats/get",
        "cluster:monitor/xpack/ml/data_frame/evaluate",
        "cluster:monitor/xpack/ml/datafeeds/get",
        "cluster:monitor/xpack/ml/datafeeds/stats/get",
        "cluster:monitor/xpack/ml/inference/get",
        "cluster:monitor/xpack/ml/inference/infer",
        "cluster:monitor/xpack/ml/inference/stats/get",
        "cluster:monitor/xpack/ml/info/get",
        "cluster:monitor/xpack/ml/job/get",
        "cluster:monitor/xpack/ml/job/model_snapshots/get",
        "cluster:monitor/xpack/ml/job/model_snapshots/upgrade/stats/get",
        "cluster:monitor/xpack/ml/job/results/buckets/get",
        "cluster:monitor/xpack/ml/job/results/categories/get",
        "cluster:monitor/xpack/ml/job/results/influencers/get",
        "cluster:monitor/xpack/ml/job/results/overall_buckets/get",
        "cluster:monitor/xpack/ml/job/results/records/get",
        "cluster:monitor/xpack/ml/job/stats/get",
        "cluster:monitor/xpack/ml/memory/stats/get",
        "cluster:monitor/xpack/ml/trained_models/deployment/infer",
        "cluster:monitor/xpack/rollup/get",
        "cluster:monitor/xpack/rollup/get/caps",
        "cluster:monitor/xpack/security/saml/metadata",
        "cluster:monitor/xpack/security/stats",
        "cluster:monitor/xpack/spatial/stats",
        "cluster:monitor/xpack/sql/async/status",
        "cluster:monitor/xpack/sql/stats/dist",
        "cluster:monitor/xpack/ssl/certificates/get",
        "cluster:monitor/xpack/usage",
        "cluster:monitor/xpack/watcher/stats/dist",
        "cluster:monitor/xpack/watcher/watch/get",
        "cluster:monitor/xpack/watcher/watch/query",
        // cluster:admin read actions
        "cluster:admin/autoscaling/get_autoscaling_capacity",
        "cluster:admin/autoscaling/get_autoscaling_policy",
        "cluster:admin/component_template/get",
        "cluster:admin/desired_balance/get",
        "cluster:admin/desired_nodes/get",
        "cluster:admin/features/get",
        "cluster:admin/fleet/secrets/get",
        "cluster:admin/idp/saml/metadata",
        "cluster:admin/idp/saml/validate",
        "cluster:admin/ilm/get",
        "cluster:admin/ilm/operation_mode/get",
        "cluster:admin/indices/dangling/find",
        "cluster:admin/indices/dangling/list",
        "cluster:admin/ingest/geoip/database/get",
        "cluster:admin/ingest/pipeline/get",
        "cluster:admin/ingest/pipeline/simulate",
        "cluster:admin/logstash/pipeline/get",
        "cluster:admin/migration/get_system_feature",
        "cluster:admin/persistent/test",
        "cluster:admin/repository/analyze",
        "cluster:admin/repository/get",
        "cluster:admin/repository/verify",
        "cluster:admin/script/get",
        "cluster:admin/script_context/get",
        "cluster:admin/script_language/get",
        "cluster:admin/scripts/painless/context",
        "cluster:admin/shutdown/get",
        "cluster:admin/shutdown/prevalidate_removal",
        "cluster:admin/slm/execute/get_expired_snapshots",
        "cluster:admin/slm/get",
        "cluster:admin/slm/stats",
        "cluster:admin/slm/status",
        "cluster:admin/snapshot/get",
        "cluster:admin/snapshot/status",
        "cluster:admin/synonym_rules/get",
        "cluster:admin/synonyms/get",
        "cluster:admin/synonyms_sets/get",
        "cluster:admin/transform/node_stats",
        "cluster:admin/transform/preview",
        "cluster:admin/transform/validate",
      ).map(Action.apply)
  }

//  val readClusterManagementMatcher: PatternsMatcher[Action] = PatternsMatcher.create {
//    RorAction.readOnlyActions ++ // todo: what about RW actions?
//      Set(
//        // cluster:monitor actions
//        "cluster:monitor/allocation/explain",
//        "cluster:monitor/allocation/stats",
//        "cluster:monitor/async_search/status",
//        "cluster:monitor/ccr/follow_info",
//        "cluster:monitor/ccr/follow_stats",
//        "cluster:monitor/ccr/stats",
//        "cluster:monitor/data_stream/lifecycle/stats",
//        "cluster:monitor/eql/async/status",
//        "cluster:monitor/fetch/health/info",
//        "cluster:monitor/health",
//        "cluster:monitor/health_api",
//        "cluster:monitor/health_api/stats",
//        "cluster:monitor/ingest/geoip/stats",
//        "cluster:monitor/main",
//        "cluster:monitor/nodes/capabilities",
//        "cluster:monitor/nodes/data_tier_usage",
//        "cluster:monitor/nodes/features",
//        "cluster:monitor/nodes/hot_threads",
//        "cluster:monitor/nodes/info",
//        "cluster:monitor/nodes/stats",
//        "cluster:monitor/nodes/usage",
//        "cluster:monitor/profiling/status/get",
//        "cluster:monitor/remote/info",
//        "cluster:monitor/settings",
//        "cluster:monitor/state",
//        "cluster:monitor/stats",
//        "cluster:monitor/stats/remote",
//        "cluster:monitor/task",
//        "cluster:monitor/task/get",
//        "cluster:monitor/tasks/lists",
//        "cluster:monitor/text_structure/find_field_structure",
//        "cluster:monitor/text_structure/find_message_structure",
//        "cluster:monitor/text_structure/findstructure",
//        "cluster:monitor/text_structure/test_grok_pattern",
//        "cluster:monitor/transform/get",
//        "cluster:monitor/transform/stats/get",
//        "cluster:monitor/update/health/info",
//        "cluster:monitor/xpack/analytics/stats",
//        "cluster:monitor/xpack/enrich/coordinator_stats",
//        "cluster:monitor/xpack/enrich/stats",
//        "cluster:monitor/xpack/eql/stats/dist",
//        "cluster:monitor/xpack/esql/get_query",
//        "cluster:monitor/xpack/esql/list_queries",
//        "cluster:monitor/xpack/esql/stats/dist",
//        "cluster:monitor/xpack/gpu_vector_indexing/stats/dist",
//        "cluster:monitor/xpack/inference/ccm/get",
//        "cluster:monitor/xpack/inference/diagnostics/get",
//        "cluster:monitor/xpack/inference/get",
//        "cluster:monitor/xpack/inference/post",
//        "cluster:monitor/xpack/inference/services/get",
//        "cluster:monitor/xpack/info",
//        "cluster:monitor/xpack/license/get",
//        "cluster:monitor/xpack/ml/autoscaling/stats/get",
//        "cluster:monitor/xpack/ml/calendars/events/get",
//        "cluster:monitor/xpack/ml/calendars/get",
//        "cluster:monitor/xpack/ml/data_frame/analytics/get",
//        "cluster:monitor/xpack/ml/data_frame/analytics/stats/get",
//        "cluster:monitor/xpack/ml/data_frame/evaluate",
//        "cluster:monitor/xpack/ml/datafeeds/get",
//        "cluster:monitor/xpack/ml/datafeeds/stats/get",
//        "cluster:monitor/xpack/ml/inference/get",
//        "cluster:monitor/xpack/ml/inference/infer",
//        "cluster:monitor/xpack/ml/inference/stats/get",
//        "cluster:monitor/xpack/ml/info/get",
//        "cluster:monitor/xpack/ml/job/get",
//        "cluster:monitor/xpack/ml/job/model_snapshots/get",
//        "cluster:monitor/xpack/ml/job/model_snapshots/upgrade/stats/get",
//        "cluster:monitor/xpack/ml/job/results/buckets/get",
//        "cluster:monitor/xpack/ml/job/results/categories/get",
//        "cluster:monitor/xpack/ml/job/results/influencers/get",
//        "cluster:monitor/xpack/ml/job/results/overall_buckets/get",
//        "cluster:monitor/xpack/ml/job/results/records/get",
//        "cluster:monitor/xpack/ml/job/stats/get",
//        "cluster:monitor/xpack/ml/memory/stats/get",
//        "cluster:monitor/xpack/ml/trained_models/deployment/infer",
//        "cluster:monitor/xpack/rollup/get",
//        "cluster:monitor/xpack/rollup/get/caps",
//        "cluster:monitor/xpack/security/saml/metadata",
//        "cluster:monitor/xpack/security/stats",
//        "cluster:monitor/xpack/spatial/stats",
//        "cluster:monitor/xpack/sql/async/status",
//        "cluster:monitor/xpack/sql/stats/dist",
//        "cluster:monitor/xpack/ssl/certificates/get",
//        "cluster:monitor/xpack/usage",
//        "cluster:monitor/xpack/watcher/stats/dist",
//        "cluster:monitor/xpack/watcher/watch/get",
//        "cluster:monitor/xpack/watcher/watch/query",
//        // cluster:admin read actions
//        "cluster:admin/autoscaling/get_autoscaling_capacity",
//        "cluster:admin/autoscaling/get_autoscaling_policy",
//        "cluster:admin/component_template/get",
//        "cluster:admin/desired_balance/get",
//        "cluster:admin/desired_nodes/get",
//        "cluster:admin/features/get",
//        "cluster:admin/fleet/secrets/get",
//        "cluster:admin/idp/saml/metadata",
//        "cluster:admin/idp/saml/validate",
//        "cluster:admin/ilm/get",
//        "cluster:admin/ilm/operation_mode/get",
//        "cluster:admin/indices/dangling/find",
//        "cluster:admin/indices/dangling/list",
//        "cluster:admin/ingest/geoip/database/get",
//        "cluster:admin/ingest/pipeline/get",
//        "cluster:admin/ingest/pipeline/simulate",
//        "cluster:admin/logstash/pipeline/get",
//        "cluster:admin/migration/get_system_feature",
//        "cluster:admin/persistent/test",
//        "cluster:admin/repository/analyze",
//        "cluster:admin/repository/get",
//        "cluster:admin/repository/verify",
//        "cluster:admin/script/get",
//        "cluster:admin/script_context/get",
//        "cluster:admin/script_language/get",
//        "cluster:admin/scripts/painless/context",
//        "cluster:admin/shutdown/get",
//        "cluster:admin/shutdown/prevalidate_removal",
//        "cluster:admin/slm/execute/get_expired_snapshots",
//        "cluster:admin/slm/get",
//        "cluster:admin/slm/stats",
//        "cluster:admin/slm/status",
//        "cluster:admin/snapshot/get",
//        "cluster:admin/snapshot/status",
//        "cluster:admin/synonym_rules/get",
//        "cluster:admin/synonyms/get",
//        "cluster:admin/synonyms_sets/get",
//        "cluster:admin/transform/node_stats",
//        "cluster:admin/transform/preview",
//        "cluster:admin/transform/validate",
//      ).map(Action.apply)
//  }

  val readActionPatternsMatcher: PatternsMatcher[Action] = PatternsMatcher.from(
    readNonClusterManagementActionPatternsMatcher, // readClusterManagementMatcher
  )

  val writeNonClusterManagementActionPatternsMatcher: PatternsMatcher[Action] = PatternsMatcher.create {
    RorAction.writeActions ++
      Set(
        // indices:admin write actions
        "indices:admin/aliases",
        "indices:admin/auto_create",
        "indices:admin/block/add",
        "indices:admin/block/remove",
        "indices:admin/cache/clear",
        "indices:admin/close",
        "indices:admin/create",
        "indices:admin/data_stream/create",
        "indices:admin/data_stream/delete",
        "indices:admin/data_stream/index/reindex",
        "indices:admin/data_stream/lazy_rollover",
        "indices:admin/data_stream/lifecycle/delete",
        "indices:admin/data_stream/lifecycle/put",
        "indices:admin/data_stream/mappings/update",
        "indices:admin/data_stream/migrate",
        "indices:admin/data_stream/modify",
        "indices:admin/data_stream/options/delete",
        "indices:admin/data_stream/options/put",
        "indices:admin/data_stream/promote",
        "indices:admin/data_stream/reindex",
        "indices:admin/data_stream/reindex_cancel",
        "indices:admin/data_stream/settings/update",
        "indices:admin/delete",
        "indices:admin/flush",
        "indices:admin/forcemerge",
        "indices:admin/ilm/remove_policy",
        "indices:admin/ilm/retry",
        "indices:admin/index/copy_lifecycle_index_metadata",
        "indices:admin/index/create_from_source",
        "indices:admin/index_template/delete",
        "indices:admin/index_template/put",
        "indices:admin/mapping/auto_put",
        "indices:admin/mapping/put",
        "indices:admin/open",
        "indices:admin/reload_analyzers",
        "indices:admin/resize",
        "indices:admin/rollover",
        "indices:admin/sample/config/delete",
        "indices:admin/sample/config/update",
        "indices:admin/seq_no/add_retention_lease",
        "indices:admin/seq_no/global_checkpoint_sync",
        "indices:admin/seq_no/remove_retention_lease",
        "indices:admin/seq_no/renew_retention_lease",
        "indices:admin/seq_no/retention_lease_background_sync",
        "indices:admin/seq_no/retention_lease_sync",
        "indices:admin/settings/update",
        "indices:admin/settings/update-internal-or-private-index",
        "indices:admin/template/delete",
        "indices:admin/template/put",
        "indices:admin/xpack/ccr/forget_follower",
        "indices:admin/xpack/ccr/put_follow",
        "indices:admin/xpack/ccr/unfollow",
        "indices:admin/xpack/downsample",
        "indices:admin/xpack/downsample_indexer",
        // indices:data/write actions
        "indices:data/write/bulk",
        "indices:data/write/bulk_shard_operations[s]",
        "indices:data/write/delete",
        "indices:data/write/delete/byquery",
        "indices:data/write/index",
        "indices:data/write/otlp/metrics",
        "indices:data/write/reindex",
        "indices:data/write/simulate/bulk",
        "indices:data/write/update",
        "indices:data/write/update/byquery",
        // indices:data/read delete actions
        "indices:data/read/async_search/delete",
        // cluster:admin/xpack write actions
        "cluster:admin/xpack/application/analytics/delete",
        "cluster:admin/xpack/application/analytics/post_event",
        "cluster:admin/xpack/application/analytics/put",
        "cluster:admin/xpack/application/search_application/delete",
        "cluster:admin/xpack/application/search_application/put",
        "cluster:admin/xpack/ccr/auto_follow_pattern/activate",
        "cluster:admin/xpack/ccr/auto_follow_pattern/delete",
        "cluster:admin/xpack/ccr/auto_follow_pattern/put",
        "cluster:admin/xpack/ccr/pause_follow",
        "cluster:admin/xpack/ccr/resume_follow",
        "cluster:admin/xpack/connector/delete",
        "cluster:admin/xpack/connector/post",
        "cluster:admin/xpack/connector/put",
        "cluster:admin/xpack/connector/secret/delete",
        "cluster:admin/xpack/connector/secret/post",
        "cluster:admin/xpack/connector/secret/put",
        "cluster:admin/xpack/connector/sync_job/cancel",
        "cluster:admin/xpack/connector/sync_job/check_in",
        "cluster:admin/xpack/connector/sync_job/claim",
        "cluster:admin/xpack/connector/sync_job/delete",
        "cluster:admin/xpack/connector/sync_job/post",
        "cluster:admin/xpack/connector/sync_job/update_error",
        "cluster:admin/xpack/connector/sync_job/update_stats",
        "cluster:admin/xpack/connector/update_api_key_id",
        "cluster:admin/xpack/connector/update_configuration",
        "cluster:admin/xpack/connector/update_error",
        "cluster:admin/xpack/connector/update_features",
        "cluster:admin/xpack/connector/update_filtering",
        "cluster:admin/xpack/connector/update_filtering/activate",
        "cluster:admin/xpack/connector/update_filtering/draft_validation",
        "cluster:admin/xpack/connector/update_index_name",
        "cluster:admin/xpack/connector/update_last_seen",
        "cluster:admin/xpack/connector/update_last_sync_stats",
        "cluster:admin/xpack/connector/update_name",
        "cluster:admin/xpack/connector/update_native",
        "cluster:admin/xpack/connector/update_pipeline",
        "cluster:admin/xpack/connector/update_scheduling",
        "cluster:admin/xpack/connector/update_service_type",
        "cluster:admin/xpack/connector/update_status",
        "cluster:admin/xpack/enrich/delete",
        "cluster:admin/xpack/enrich/execute",
        "cluster:admin/xpack/enrich/internal_execute",
        "cluster:admin/xpack/enrich/put",
        "cluster:admin/xpack/enrich/reindex",
        "cluster:admin/xpack/esql/view/delete",
        "cluster:admin/xpack/esql/view/put",
        "cluster:admin/xpack/inference/ccm/delete",
        "cluster:admin/xpack/inference/ccm/put",
        "cluster:admin/xpack/inference/delete",
        "cluster:admin/xpack/inference/put",
        "cluster:admin/xpack/inference/update",
        "cluster:admin/xpack/license/delete",
        "cluster:admin/xpack/license/put",
        "cluster:admin/xpack/license/start_basic",
        "cluster:admin/xpack/license/start_trial",
        "cluster:admin/xpack/ml/calendars/delete",
        "cluster:admin/xpack/ml/calendars/events/delete",
        "cluster:admin/xpack/ml/calendars/events/post",
        "cluster:admin/xpack/ml/calendars/jobs/update",
        "cluster:admin/xpack/ml/calendars/put",
        "cluster:admin/xpack/ml/data_frame/analytics/delete",
        "cluster:admin/xpack/ml/data_frame/analytics/put",
        "cluster:admin/xpack/ml/data_frame/analytics/start",
        "cluster:admin/xpack/ml/data_frame/analytics/stop",
        "cluster:admin/xpack/ml/data_frame/analytics/update",
        "cluster:admin/xpack/ml/datafeed/start",
        "cluster:admin/xpack/ml/datafeed/stop",
        "cluster:admin/xpack/ml/datafeeds/delete",
        "cluster:admin/xpack/ml/datafeeds/put",
        "cluster:admin/xpack/ml/datafeeds/update",
        "cluster:admin/xpack/ml/delete_expired_data",
        "cluster:admin/xpack/ml/filters/delete",
        "cluster:admin/xpack/ml/filters/put",
        "cluster:admin/xpack/ml/filters/update",
        "cluster:admin/xpack/ml/inference/clear_model_cache",
        "cluster:admin/xpack/ml/inference/delete",
        "cluster:admin/xpack/ml/inference/model_aliases/delete",
        "cluster:admin/xpack/ml/inference/model_aliases/put",
        "cluster:admin/xpack/ml/inference/put",
        "cluster:admin/xpack/ml/job/close",
        "cluster:admin/xpack/ml/job/data/post",
        "cluster:admin/xpack/ml/job/delete",
        "cluster:admin/xpack/ml/job/flush",
        "cluster:admin/xpack/ml/job/forecast",
        "cluster:admin/xpack/ml/job/forecast/delete",
        "cluster:admin/xpack/ml/job/model_snapshots/delete",
        "cluster:admin/xpack/ml/job/model_snapshots/revert",
        "cluster:admin/xpack/ml/job/model_snapshots/update",
        "cluster:admin/xpack/ml/job/model_snapshots/upgrade",
        "cluster:admin/xpack/ml/job/model_snapshots/upgrade/cancel",
        "cluster:admin/xpack/ml/job/open",
        "cluster:admin/xpack/ml/job/persist",
        "cluster:admin/xpack/ml/job/put",
        "cluster:admin/xpack/ml/job/reset",
        "cluster:admin/xpack/ml/job/update",
        "cluster:admin/xpack/ml/trained_models/deployment/clear_cache",
        "cluster:admin/xpack/ml/trained_models/deployment/start",
        "cluster:admin/xpack/ml/trained_models/deployment/stop",
        "cluster:admin/xpack/ml/trained_models/deployment/update",
        "cluster:admin/xpack/ml/trained_models/part/put",
        "cluster:admin/xpack/ml/trained_models/vocabulary/put",
        "cluster:admin/xpack/ml/upgrade_mode",
        "cluster:admin/xpack/monitoring/bulk",
        "cluster:admin/xpack/monitoring/migrate/alerts",
        "cluster:admin/xpack/query_rules/delete",
        "cluster:admin/xpack/query_rules/put",
        "cluster:admin/xpack/query_rules/rule/delete",
        "cluster:admin/xpack/query_rules/rule/put",
        "cluster:admin/xpack/query_rules/test",
        "cluster:admin/xpack/rollup/delete",
        "cluster:admin/xpack/rollup/put",
        "cluster:admin/xpack/rollup/start",
        "cluster:admin/xpack/rollup/stop",
        "cluster:admin/xpack/security/api_key/bulk_update",
        "cluster:admin/xpack/security/api_key/create",
        "cluster:admin/xpack/security/api_key/grant",
        "cluster:admin/xpack/security/api_key/invalidate",
        "cluster:admin/xpack/security/api_key/update",
        "cluster:admin/xpack/security/cache/clear",
        "cluster:admin/xpack/security/cross_cluster/api_key/create",
        "cluster:admin/xpack/security/cross_cluster/api_key/update",
        "cluster:admin/xpack/security/delegate_pki",
        "cluster:admin/xpack/security/enroll/kibana",
        "cluster:admin/xpack/security/enroll/node",
        "cluster:admin/xpack/security/oidc/authenticate",
        "cluster:admin/xpack/security/oidc/logout",
        "cluster:admin/xpack/security/oidc/prepare",
        "cluster:admin/xpack/security/privilege/cache/clear",
        "cluster:admin/xpack/security/privilege/delete",
        "cluster:admin/xpack/security/privilege/put",
        "cluster:admin/xpack/security/profile/activate",
        "cluster:admin/xpack/security/profile/put/data",
        "cluster:admin/xpack/security/profile/set_enabled",
        "cluster:admin/xpack/security/realm/cache/clear",
        "cluster:admin/xpack/security/role/bulk_delete",
        "cluster:admin/xpack/security/role/bulk_put",
        "cluster:admin/xpack/security/role/delete",
        "cluster:admin/xpack/security/role/put",
        "cluster:admin/xpack/security/role_mapping/delete",
        "cluster:admin/xpack/security/role_mapping/put",
        "cluster:admin/xpack/security/roles/cache/clear",
        "cluster:admin/xpack/security/saml/authenticate",
        "cluster:admin/xpack/security/saml/complete_logout",
        "cluster:admin/xpack/security/saml/invalidate",
        "cluster:admin/xpack/security/saml/logout",
        "cluster:admin/xpack/security/saml/prepare",
        "cluster:admin/xpack/security/service_account/token/create",
        "cluster:admin/xpack/security/service_account/token/delete",
        "cluster:admin/xpack/security/settings/update",
        "cluster:admin/xpack/security/token/create",
        "cluster:admin/xpack/security/token/invalidate",
        "cluster:admin/xpack/security/token/refresh",
        "cluster:admin/xpack/security/user/change_password",
        "cluster:admin/xpack/security/user/delete",
        "cluster:admin/xpack/security/user/put",
        "cluster:admin/xpack/security/user/set_enabled",
        "cluster:admin/xpack/watcher/service",
        "cluster:admin/xpack/watcher/settings/update",
        "cluster:admin/xpack/watcher/watch/ack",
        "cluster:admin/xpack/watcher/watch/activate",
        "cluster:admin/xpack/watcher/watch/delete",
        "cluster:admin/xpack/watcher/watch/execute",
        "cluster:admin/xpack/watcher/watch/put",
      ).map(Action.apply) ++
      Set(
        "cluster:admin/autoscaling/delete_autoscaling_policy",
        "cluster:admin/autoscaling/put_autoscaling_policy",
        "cluster:admin/component_template/delete",
        "cluster:admin/component_template/put",
        "cluster:admin/deprecation/cache/reset",
        "cluster:admin/desired_balance/reset",
        "cluster:admin/desired_nodes/delete",
        "cluster:admin/desired_nodes/update",
        "cluster:admin/features/reset",
        "cluster:admin/fleet/secrets/delete",
        "cluster:admin/fleet/secrets/post",
        "cluster:admin/idp/saml/init",
        "cluster:admin/idp/saml/sp/delete",
        "cluster:admin/idp/saml/sp/put",
        "cluster:admin/ilm/_move/post",
        "cluster:admin/ilm/delete",
        "cluster:admin/ilm/put",
        "cluster:admin/ilm/start",
        "cluster:admin/ilm/stop",
        "cluster:admin/indices/dangling/delete",
        "cluster:admin/indices/dangling/import",
        "cluster:admin/ingest/geoip/database/delete",
        "cluster:admin/ingest/geoip/database/put",
        "cluster:admin/ingest/pipeline/delete",
        "cluster:admin/ingest/pipeline/put",
        "cluster:admin/logstash/pipeline/delete",
        "cluster:admin/logstash/pipeline/put",
        "cluster:admin/migrate_to_data_tiers",
        "cluster:admin/migration/post_system_feature",
        "cluster:admin/nodes/reload_secure_settings",
        "cluster:admin/persistent/completion",
        "cluster:admin/persistent/remove",
        "cluster:admin/persistent/start",
        "cluster:admin/persistent/update_status",
        "cluster:admin/projects/delete",
        "cluster:admin/projects/put",
        "cluster:admin/reindex/rethrottle",
        "cluster:admin/repository/_cleanup",
        "cluster:admin/repository/delete",
        "cluster:admin/repository/put",
        "cluster:admin/reroute",
        "cluster:admin/script/delete",
        "cluster:admin/script/put",
        "cluster:admin/scripts/painless/execute",
        "cluster:admin/settings/update",
        "cluster:admin/shutdown/create",
        "cluster:admin/shutdown/delete",
        "cluster:admin/slm/delete",
        "cluster:admin/slm/execute",
        "cluster:admin/slm/execute-retention",
        "cluster:admin/slm/put",
        "cluster:admin/slm/start",
        "cluster:admin/slm/stop",
        "cluster:admin/snapshot/clone",
        "cluster:admin/snapshot/create",
        "cluster:admin/snapshot/delete",
        "cluster:admin/snapshot/mount",
        "cluster:admin/snapshot/restore",
        "cluster:admin/synonym_rules/delete",
        "cluster:admin/synonym_rules/put",
        "cluster:admin/synonyms/delete",
        "cluster:admin/synonyms/put",
        "cluster:admin/tasks/cancel",
        "cluster:admin/transform/delete",
        "cluster:admin/transform/put",
        "cluster:admin/transform/reset",
        "cluster:admin/transform/schedule_now",
        "cluster:admin/transform/start",
        "cluster:admin/transform/stop",
        "cluster:admin/transform/update",
        "cluster:admin/transform/upgrade",
        "cluster:admin/transform/upgrade_mode",
        "cluster:admin/voting_config/add_exclusions",
        "cluster:admin/voting_config/clear_exclusions",
      ).map(Action.apply)
  }

//  val writeClusterManagementMatcher: PatternsMatcher[Action] = PatternsMatcher.create {
//    RorAction.writeActions ++
//      Set(
//        "cluster:admin/autoscaling/delete_autoscaling_policy",
//        "cluster:admin/autoscaling/put_autoscaling_policy",
//        "cluster:admin/component_template/delete",
//        "cluster:admin/component_template/put",
//        "cluster:admin/deprecation/cache/reset",
//        "cluster:admin/desired_balance/reset",
//        "cluster:admin/desired_nodes/delete",
//        "cluster:admin/desired_nodes/update",
//        "cluster:admin/features/reset",
//        "cluster:admin/fleet/secrets/delete",
//        "cluster:admin/fleet/secrets/post",
//        "cluster:admin/idp/saml/init",
//        "cluster:admin/idp/saml/sp/delete",
//        "cluster:admin/idp/saml/sp/put",
//        "cluster:admin/ilm/_move/post",
//        "cluster:admin/ilm/delete",
//        "cluster:admin/ilm/put",
//        "cluster:admin/ilm/start",
//        "cluster:admin/ilm/stop",
//        "cluster:admin/indices/dangling/delete",
//        "cluster:admin/indices/dangling/import",
//        "cluster:admin/ingest/geoip/database/delete",
//        "cluster:admin/ingest/geoip/database/put",
//        "cluster:admin/ingest/pipeline/delete",
//        "cluster:admin/ingest/pipeline/put",
//        "cluster:admin/logstash/pipeline/delete",
//        "cluster:admin/logstash/pipeline/put",
//        "cluster:admin/migrate_to_data_tiers",
//        "cluster:admin/migration/post_system_feature",
//        "cluster:admin/nodes/reload_secure_settings",
//        "cluster:admin/persistent/completion",
//        "cluster:admin/persistent/remove",
//        "cluster:admin/persistent/start",
//        "cluster:admin/persistent/update_status",
//        "cluster:admin/projects/delete",
//        "cluster:admin/projects/put",
//        "cluster:admin/reindex/rethrottle",
//        "cluster:admin/repository/_cleanup",
//        "cluster:admin/repository/delete",
//        "cluster:admin/repository/put",
//        "cluster:admin/reroute",
//        "cluster:admin/script/delete",
//        "cluster:admin/script/put",
//        "cluster:admin/scripts/painless/execute",
//        "cluster:admin/settings/update",
//        "cluster:admin/shutdown/create",
//        "cluster:admin/shutdown/delete",
//        "cluster:admin/slm/delete",
//        "cluster:admin/slm/execute",
//        "cluster:admin/slm/execute-retention",
//        "cluster:admin/slm/put",
//        "cluster:admin/slm/start",
//        "cluster:admin/slm/stop",
//        "cluster:admin/snapshot/clone",
//        "cluster:admin/snapshot/create",
//        "cluster:admin/snapshot/delete",
//        "cluster:admin/snapshot/mount",
//        "cluster:admin/snapshot/restore",
//        "cluster:admin/synonym_rules/delete",
//        "cluster:admin/synonym_rules/put",
//        "cluster:admin/synonyms/delete",
//        "cluster:admin/synonyms/put",
//        "cluster:admin/tasks/cancel",
//        "cluster:admin/transform/delete",
//        "cluster:admin/transform/put",
//        "cluster:admin/transform/reset",
//        "cluster:admin/transform/schedule_now",
//        "cluster:admin/transform/start",
//        "cluster:admin/transform/stop",
//        "cluster:admin/transform/update",
//        "cluster:admin/transform/upgrade",
//        "cluster:admin/transform/upgrade_mode",
//        "cluster:admin/voting_config/add_exclusions",
//        "cluster:admin/voting_config/clear_exclusions",
//      ).map(Action.apply)
//  }

  val writeActionPatternsMatcher: PatternsMatcher[Action] = PatternsMatcher.from(
    writeNonClusterManagementActionPatternsMatcher, // writeClusterManagementMatcher
  )

}
