version: "3.7"
services:

  es:
    build:
      context: .
      dockerfile: ror/es/${DOCKERFILE}
      args:
        ES_VERSION: $ELK_VERSION
        ROR_VERSION: $ROR_VERSION
    ports:
      - "19200:9200"
      - "19300:9300"
      - "5000:58672"
    environment:
      - cluster.name=es-cluster
      - node.name=es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58672"
      - ES_VERSION=$ELK_VERSION
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es-ror-proxy:
    image: mitmproxy/mitmproxy
    command:
      mitmdump --set validate_inbound_headers=false --mode reverse:https://es:9200 --ssl-insecure --verbose
    depends_on:
      - es
    networks:
      - es-network

  kbn-ror:
    build:
      context: .
      dockerfile: ror/kbn/Dockerfile
      args:
        ELK_VERSION: $ELK_VERSION
        ROR_KBN: $ROR_VERSION
    ports:
      - "15601:5601"
    environment:
      ELASTIC_USER_PASSWORD: elastic
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  es-network:
    driver: bridge
