ARG ES_VERSION

FROM ror-builder AS build

ARG ES_VERSION

RUN /ror/bin/build-ror-plugin.sh $ES_VERSION &&\
    ls -h /ror/builds &&\
    mv /ror/builds/readonlyrest*es${ES_VERSION}.zip /ror/builds/ror.zip

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
COPY --from=build /ror/builds/ror.zip /tmp/ror.zip

ARG ES_CLOUD_PROXY_ADDRESS
ARG ES_CLOUD_SERVER_NAME

RUN  cd /usr/share/elasticsearch/config &&\
     mkdir -p /usr/share/elasticsearch/config/certs/ca

COPY es/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY es/readonlyrest.yml /usr/share/elasticsearch/config/readonlyrest.yml
COPY certs-generator/certs/ror-cluster /usr/share/elasticsearch/config/certs/ror-cluster

USER root

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch file:///tmp/ror.zip &&\
    jdk/bin/java -jar plugins/readonlyrest/ror-tools.jar patch

ENV ES_CLOUD_PROXY_ADDRESS=$ES_CLOUD_PROXY_ADDRESS
ENV ES_CLOUD_SERVER_NAME=$ES_CLOUD_SERVER_NAME

USER elasticsearch
