version: "3.8"
services:

  es:
    build:
      context: .
      dockerfile: ror/es/Dockerfile
      args:
        ES_VERSION: $ELK_VERSION
    hostname: es
    container_name: es
    depends_on:
      - ldap
      - lagsimulator
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5000:58672" #remote debugger port
      - "9010:9010" # jvisualvm jmx connection port
    environment:
      - cluster.name=es-cluster
      - node.name=es-ror
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m 
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58672 
      -Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.port=9010
      -Dcom.sun.management.jmxremote.local.only=false
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.rmi.port=9010
      -Djava.rmi.server.hostname=127.0.0.1"
      - ES_VERSION=$ELK_VERSION
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  lagsimulator:
    build:
      context: .
      dockerfile: lag-simulator/Dockerfile
    hostname: simulatedlag
    container_name: simulatedlag
    depends_on:
      - ldap
    networks:
      - es-network

  ldap:
    image: nitnelave/lldap:stable
    user: "33:33"
    hostname: ldap
    container_name: ldap
    ports:
      - "3890:3890" # ldap port
      - "17170:17170" # ldap frontend
    volumes:
      - "./ldap/data/:/data"
    environment:
      - LLDAP_JWT_SECRET=secret
      - LLDAP_LDAP_USER_PASS=password
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
    networks:
      - es-network

networks:
  es-network:
    driver: bridge
