FROM docker.elastic.co/kibana/kibana:7.15.0
COPY es714x/build/distributions/readonlyrest_kbn_enterprise-1.38.0-pre1_es7.15.0.zip /tmp
RUN bin/kibana-plugin install file:///tmp/readonlyrest_kbn_enterprise-1.38.0-pre1_es7.15.0.zip
RUN node/bin/node plugins/readonlyrestkbn/ror-tools.js patch
