ARG ES_VERSION

FROM ror-builder AS build

ARG ES_VERSION

RUN /ror/bin/build-ror-plugin.sh $ES_VERSION &&\
    ls -h /ror/builds &&\
    mv /ror/builds/readonlyrest*es${ES_VERSION}.zip /ror/builds/ror.zip

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
COPY --from=build /ror/builds/ror.zip /tmp/ror.zip

COPY certs/elastic-certificates.p12 /usr/share/elasticsearch/config/
COPY ror/es/readonlyrest.yml /usr/share/elasticsearch/config/readonlyrest.yml
COPY ror/es/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY .base/es/install-ror-es-using-file.sh /tmp/install-ror.sh

USER root

RUN /tmp/install-ror.sh

USER elasticsearch
