ARG ES_VERSION
ARG ES_CLOUD_PROXY_ADDRESS
ARG ES_CLOUD_SERVER_NAME

FROM ror-builder AS build

ARG ES_VERSION
ARG ES_CLOUD_PROXY_ADDRESS
ARG ES_CLOUD_SERVER_NAME

RUN /ror/docker-based-builder/ror-builder/run-ror-gradle-builder.sh $ES_VERSION &&\
    ls -h /ror/builds &&\
    mv /ror/builds/readonlyrest*es${ES_VERSION}.zip /ror/builds/ror.zip

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
COPY --from=build /ror/builds/ror.zip /tmp/ror.zip

ARG ES_VERSION
ARG ROR_VERSION
ARG ES_CLOUD_PROXY_ADDRESS
ARG ES_CLOUD_SERVER_NAME

COPY certs/ /usr/share/elasticsearch/config/
COPY ror/es/readonlyrest.yml /usr/share/elasticsearch/config/readonlyrest.yml
COPY ror/es/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY ror/es/log4j2.properties /usr/share/elasticsearch/config/log4j2.properties
COPY .base/es/install-ror-es-using-file.sh /tmp/install-ror.sh

USER root

RUN /tmp/install-ror.sh

USER elasticsearch
