ARG ES_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

ARG ES_VERSION
ARG ROR_FILE

COPY certs/elastic-certificates.p12 /usr/share/elasticsearch/config/
COPY ror/es/readonlyrest.yml /usr/share/elasticsearch/config/readonlyrest.yml
COPY ror/es/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY .base/es/install-ror-es-using-file.sh /tmp/install-ror.sh
COPY $ROR_FILE /tmp/ror.zip

USER root

RUN /tmp/install-ror.sh

USER elasticsearch
