version: "3.8"
services:

  es01:
    build:
      context: .
      dockerfile: xpack/es/Dockerfile
      args:
        ES_VERSION: $ES_VERSION
    ports:
      - "9201:9200"
      - "9301:9300"
      - "5001:58672"
    environment:
      - cluster.name=es-cluster
      - node.name=es01-master
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01-master,es02-master,es03-master
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=none
      - xpack.security.transport.ssl.client_authentication=none
      - xpack.security.transport.ssl.keystore.path=elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=elastic-certificates.p12
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.verification_mode=none
      - xpack.security.http.ssl.client_authentication=none
      - xpack.security.http.ssl.keystore.path=elastic-certificates.p12
      - xpack.security.http.ssl.truststore.path=elastic-certificates.p12
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58672"
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es02:
    build:
      context: .
      dockerfile: xpack/es/Dockerfile
      args:
        ES_VERSION: $ES_VERSION
    ports:
      - "9202:9200"
      - "9302:9300"
      - "5002:58672"
    environment:
      - cluster.name=es-cluster
      - node.name=es02-master
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01-master,es02-master,es03-master
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=none
      - xpack.security.transport.ssl.client_authentication=none
      - xpack.security.transport.ssl.keystore.path=elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=elastic-certificates.p12
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.verification_mode=none
      - xpack.security.http.ssl.client_authentication=none
      - xpack.security.http.ssl.keystore.path=elastic-certificates.p12
      - xpack.security.http.ssl.truststore.path=elastic-certificates.p12
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58672"
    healthcheck:
      test: [ "CMD", "curl", "-fk", "-u", "admin:container", "https://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es03:
    build:
      context: .
      dockerfile: .base/es/${ES_DOCKERFILE}
      args:
        ES_VERSION: $ES_VERSION
        ROR_VERSION: $ROR_ES_VERSION
        ROR_FILE: $ES_ROR_FILE
    ports:
      - "9203:9200"
      - "9303:9300"
      - "5003:58672"
    environment:
      - cluster.name=es-cluster
      - node.name=es03-master
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01-master,es02-master,es03-master
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58672"
    healthcheck:
      test: [ "CMD", "curl", "-fk", "-u", "admin:container", "https://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es-ror-proxy:
    image: mitmproxy/mitmproxy
    command:
      mitmdump --set validate_inbound_headers=false --mode reverse:https://es03:9200 --ssl-insecure --verbose
    depends_on:
      - es03
    networks:
      - es-network

  kbn-ror:
    build:
      context: .
      dockerfile: .base/kbn/${KBN_DOCKERFILE}
      args:
        KBN_VERSION: $KBN_VERSION
        ROR_VERSION: $ROR_KBN_VERSION
        ROR_FILE: $KBN_ROR_FILE
        ROR_ACTIVATION_KEY: $ROR_ACTIVATION_KEY
    ports:
      - "15601:5601"
    environment:
      ELASTIC_USER_PASSWORD: elastic
      ES_API_URL: https://es-ror-proxy:8080
    depends_on:
      es03:
        condition: service_healthy
      es-ror-proxy:
        condition: service_started
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es-xpack-proxy:
    image: mitmproxy/mitmproxy
    command:
      mitmdump --set validate_inbound_headers=false --mode reverse:https://es02:9200 --ssl-insecure --verbose
    depends_on:
      - es02
    networks:
      - es-network

  kbn-xpack:
    build:
      context: .
      dockerfile: xpack/kbn/Dockerfile
      args:
        KBN_VERSION: $KBN_VERSION
    ports:
      - "25601:5601"
    environment:
      ELASTIC_USER_PASSWORD: elastic
      ES_API_URL: https://es-xpack-proxy:8080
    depends_on:
      es02:
        condition: service_healthy
      es-xpack-proxy:
        condition: service_started
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  es-network:
    driver: bridge
