ARG ES_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

ARG ES_VERSION
ARG ROR_VERSION
ARG ES_CLOUD_PROXY_ADDRESS
ARG ES_CLOUD_SERVER_NAME

RUN  cd /usr/share/elasticsearch/config &&\
     mkdir -p /usr/share/elasticsearch/config/certs/ca

COPY es/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY es/readonlyrest.yml /usr/share/elasticsearch/config/readonlyrest.yml
COPY certs-generator/certs/ror-cluster /usr/share/elasticsearch/config/certs/ror-cluster

USER root

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch "https://api.beshu.tech/download/es?esVersion=$ES_VERSION&pluginVersion=$ROR_VERSION" &&\
    jdk/bin/java -jar plugins/readonlyrest/ror-tools.jar patch

ENV ES_CLOUD_PROXY_ADDRESS=$ES_CLOUD_PROXY_ADDRESS
ENV ES_CLOUD_SERVER_NAME=$ES_CLOUD_SERVER_NAME

USER elasticsearch
