kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30010
    hostPort: 19200
  - containerPort: 30011
    hostPort: 15601
- role: worker
- role: worker
