version: '3'

services:

  es: 
    image: coutopl/es_7.17.0_ror_1.38.0-eck-poc
    ports: 
    - 9202:9200
    environment:
    - discovery.type=single-node
    volumes:
    - ./readonlyrest.yml:/usr/share/elasticsearch/config/readonlyrest.yml

  kbn:
    image: coutopl/kbn_7.17.0_ror_1.38.0-eck-poc
    depends_on:
    - es
    ports:
    - 5602:5601
    volumes:
    - ./kibana.yml:/usr/share/kibana/config/kibana.yml
