version: "3.8"
services:

  es-ror:
    build:
      context: .
      dockerfile: .base/es/${ES_DOCKERFILE}
      args:
        ES_VERSION: $ES_VERSION
        ROR_VERSION: $ROR_ES_VERSION
        ROR_FILE: $ES_ROR_FILE
        ES_CLOUD_PROXY_ADDRESS: $ES_CLOUD_PROXY_ADDRESS
        ES_CLOUD_SERVER_NAME: $ES_CLOUD_SERVER_NAME
    ports:
      - "19200:9200"
      - "19300:9300"
      - "5000:58672"
    environment:
      - cluster.name=ror-es-cluster
      - node.name=es-ror-single
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58672"
      - ES_VERSION=$ES_VERSION
      - ES_CLOUD_PROXY_ADDRESS=$ES_CLOUD_PROXY_ADDRESS
      - ES_CLOUD_SERVER_NAME=$ES_CLOUD_SERVER_NAME
    healthcheck:
      test: [ "CMD", "curl", "-fk", "-u", "admin:admin", "http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    networks:
      - es-ror-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kbn-ror:
    build:
      context: .
      dockerfile: .base/kbn/${KBN_DOCKERFILE}
      args:
        KBN_VERSION: $KBN_VERSION
        ROR_VERSION: $ROR_KBN_VERSION
        ROR_FILE: $KBN_ROR_FILE
        ROR_ACTIVATION_KEY: $ROR_ACTIVATION_KEY
    depends_on:
      es-ror:
        condition: service_healthy
    ports:
      - "15601:5601"
    environment:
      ELASTIC_USER_PASSWORD: elastic
      ES_API_URL: http://es-ror:9200
    networks:
      - es-ror-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  es-ror-network:
    driver: bridge

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/certs-generator/certs
