version: "3.7"
services:

  es-ror:
    build:
      context: .
      dockerfile: es/${DOCKERFILE}
      args:
        ES_VERSION: $ELK_VERSION
        ROR_VERSION: $ROR_VERSION
        ES_CLOUD_PROXY_ADDRESS: $ES_CLOUD_PROXY_ADDRESS
        ES_CLOUD_SERVER_NAME: $ES_CLOUD_SERVER_NAME
    ports:
      - "19200:9200"
      - "19300:9300"
      - "5000:58672"
    environment:
      - cluster.name=ror-es-cluster
      - node.name=es-ror-single
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58672"
      - ES_VERSION=$ELK_VERSION
    networks:
      - es-ror-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kbn-ror:
    build:
      context: .
      dockerfile: kbn/Dockerfile
      args:
        ELK_VERSION: $ELK_VERSION
        ROR_VERSION: $ROR_VERSION
    depends_on:
      - "es-ror"
    ports:
      - "15601:5601"
    environment:
      ELASTIC_USER_PASSWORD: elastic
    networks:
      - es-ror-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  es-ror-network:
    driver: bridge

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/certs-generator/certs
