/*
 *    This file is part of ReadonlyREST.
 *
 *    ReadonlyREST is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    ReadonlyREST is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with ReadonlyREST.  If not, see http://www.gnu.org/licenses/
 */
plugins {
    id "readonlyrest.plugin-common-conventions"
}

apply from: "$rootDir/es7-base/module.gradle"

dependencies {
    compileOnly     group: 'org.locationtech.spatial4j', name: 'spatial4j',                 version: '0.7'
}

// because of https://github.com/elastic/elasticsearch/issues/68889 (for ES 7.11.0)
configurations.configureEach {
    exclude group: 'org.elasticsearch', module: 'elasticsearch-plugin-classloader'
}
