apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.14.0
  image: beshultd/elasticsearch-readonlyrest:8.14.0-ror-1.59.0
  nodeSets:
    - name: default
      count: 2
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
              env:
                - name: I_UNDERSTAND_IMPLICATION_OF_ES_PATCHING
                  value: "yes"
                - name: INTERNAL_USR_PASS
                  valueFrom:
                    secretKeyRef:
                      name: quickstart-es-internal-users
                      key: elastic-internal
                - name: INTERNAL_PROBE_PASS
                  valueFrom:
                    secretKeyRef:
                      name: quickstart-es-internal-users
                      key: elastic-internal-probe
                - name: KIBANA_SERVICE_ACCOUNT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: quickstart-kibana-user
                      key: token
                - name: ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: admin-password-secret
                      key: ADMIN_PASSWORD
                - name: ES_JAVA_OPTS
                  value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888 -Dbootstrap.system_call_filter=false
              volumeMounts:
                - name: config-ror
                  mountPath: /usr/share/elasticsearch/config/readonlyrest.yml
                  subPath: readonlyrest.yml
                - name: config-log4j2
                  mountPath: /usr/share/elasticsearch/config/log4j2.properties
                  subPath: log4j2.properties
          volumes:
            - name: config-ror
              configMap:
                name: config-readonlyrest.yml
            - name: config-log4j2
              configMap:
                name: config-log4j2.properties.yml