apiVersion: v1
kind: Service
metadata:
  name: kbn-np
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30011
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
