apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: ${KBN_VERSION}
  image: beshultd/kibana-readonlyrest:${KBN_VERSION}-ror-latest
  count: 2
  elasticsearchRef:
    name: quickstart
  config:
    readonlyrest_kbn.store_sessions_in_index: true
    readonlyrest_kbn.cookiePass: "12345678901234567890123456789012345678901234567890"
    readonlyrest_kbn.logLevel: "info"
  podTemplate:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: kibana
          env:
            - name: ROR_ACTIVATION_KEY
              value: "<YOUR_ACTIVATION_KEY/>"
            - name: I_UNDERSTAND_AND_ACCEPT_KBN_PATCHING # ROR 1.61.0 and newer
              value: "yes"
            - name: I_UNDERSTAND_IMPLICATION_OF_KBN_PATCHING # pre ROR 1.61.0
              value: "yes"
