apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.11.3
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              image: coutopl/elasticsearch-readonlyrest:8.11.3-ror-latest
              imagePullPolicy: Always
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
              env:
                - name: I_UNDERSTAND_IMPLICATION_OF_ES_PATCHING
                  value: "yes"
