apiVersion: v1
data:
   readonlyrest.yml: |
     readonlyrest:
       access_control_rules:
       
       - name: "Kibana service account"
         verbosity: error
         token_authentication:
           token: "Bearer ${KIBANA_SERVICE_ACCOUNT_TOKEN}" 
           username: service_account
     
       - name: "PROBE"
         verbosity: error
         auth_key: "elastic-internal-probe:${INTERNAL_PROBE_PASS}"

       - name: "ELASTIC-INTERNAL"
         verbosity: error
         auth_key: "elastic-internal:${INTERNAL_USR_PASS}"

       - name: "Admin access"
         type: allow
         auth_key: "admin:${ADMIN_PASSWORD}"

kind: ConfigMap
metadata:
  name: config-readonlyrest.yml
