package tech.beshu.ror.integration.plugin

import tech.beshu.ror.integration.suites.SnapshotAndRestoreApiSuite
import tech.beshu.ror.integration.utils.SingletonPluginTestSupport

class SnapshotAndRestoreApiPluginTests extends SnapshotAndRestoreApiSuite with SingletonPluginTestSupport