FROM docker.elastic.co/kibana/kibana:8.7.1
#COPY rorkbn.zip /tmp
#RUN bin/kibana-plugin install file:///tmp/rorkbn.zip
RUN bin/kibana-plugin install "https://api.beshu.tech/download/kbn?esVersion=8.7.1&pluginVersion=1.53.0&edition=kbn_universal&email=eck-example%40readonlyrest.com"
RUN node/bin/node plugins/readonlyrestkbn/ror-tools.js patch
