FROM docker.elastic.co/kibana/kibana:8.8.2
RUN bin/kibana-plugin install "https://api.beshu.tech/download/kbn?esVersion=8.8.2&pluginVersion=1.49.1&edition=kbn_universal&email=support%40readonlyrest.com"
RUN node/bin/node plugins/readonlyrestkbn/ror-tools.js patch
