FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.1
RUN bin/elasticsearch-plugin install --batch "https://api.beshu.tech/download/es?esVersion=8.11.1&pluginVersion=1.53.0&email=eck-example%40readonlyrest.com"
USER root
RUN /usr/share/elasticsearch/jdk/bin/java -jar /usr/share/elasticsearch/plugins/readonlyrest/ror-tools.jar patch
USER 1000