kind: Secret
apiVersion: v1
metadata:
  name: amin-role-secret
stringData:
  roles.yml: |-
    admins:
      cluster:
      - all
      indices:
      - names:
          - "*"
        privileges:
          - all
