apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.6.1
  image: coutopl/es_8.6.1_ror_1.47.0-eck-poc
  auth:
    roles:
    - secretName: amin-role-secret
  nodeSets:
  - name: default
    count: 1
    config:
      xpack.security.authc.anonymous.username: anonymous
      xpack.security.authc.anonymous.roles: superuser, admins
      xpack.security.authc.anonymous.authz_exception: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 1Gi
              cpu: 1024m
          env:
#          - name: xpack.security.enabled
#            value: "false"
          - name: INTERNAL_USR_PASS
            valueFrom:
              secretKeyRef:
                name: quickstart-es-internal-users
                key: elastic-internal
          - name: INTERNAL_PROBE_PASS
            valueFrom:
              secretKeyRef:
                name: quickstart-es-internal-users
                key: elastic-internal-probe
#          - name: KIBANA_USER_PASS
#            valueFrom:
#              secretKeyRef:
#                name: quickstart-kibana-user
#                key: default-quickstart-kibana-user
          volumeMounts:
          - name: config
            mountPath: /usr/share/elasticsearch/config/readonlyrest.yml
            subPath: readonlyrest.yml
          - name: config2
            mountPath: /usr/share/elasticsearch/config/log4j2.properties
            subPath: log4j2.properties
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
        volumes:
        - name: config
          configMap:
            name: ror-config
        - name: config2
          configMap:
            name: log4j2-config
