apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.10.4
  image: coutopl/kbn_8.10.4_ror_1.52.0
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    readonlyrest_kbn.cookiePass: "12345678901234567890123456789012345678901234567890"
    readonlyrest_kbn.logLevel: "trace"
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 2048Mi
            cpu: 2