apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.11.1
  image: coutopl/kbn_8.11.1_ror_1.53.0
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    readonlyrest_kbn.cookiePass: "12345678901234567890123456789012345678901234567890"
    readonlyrest_kbn.logLevel: "trace"
  podTemplate:
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: kibana
          resources:
            requests:
              memory: 2048Mi
              cpu: 2