/*
 *    This file is part of ReadonlyREST.
 *
 *    ReadonlyREST is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    ReadonlyREST is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with ReadonlyREST.  If not, see http://www.gnu.org/licenses/
 */

package tech.beshu.ror.gradle.utils;

import org.gradle.api.GradleException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

/** Reads the dependencies of a published POM and renders the POMs we publish to the libs store. */
public final class MavenPoms {

  /** A {@code groupId:artifactId} pair; the version is always the ES version being mirrored. */
  public record Coordinate(String groupId, String artifactId) {

    /** The artifact's directory in a maven repository layout, without the version. */
    public String repositoryPath() {
      return groupId.replace('.', '/') + "/" + artifactId;
    }
  }

  public record Dependency(String groupId, String artifactId, String version, String scope) {

    public Dependency withVersion(String newVersion) {
      return new Dependency(groupId, artifactId, newVersion, scope);
    }
  }

  private static final String DEFAULT_SCOPE = "compile";

  private MavenPoms() {}

  /**
   * The direct dependencies a POM declares. Only the project's own {@code <dependencies>} is read, so a
   * {@code <dependencyManagement>} section (which declares versions rather than dependencies) is ignored.
   */
  public static List<Dependency> parseDependencies(String pomXml) {
    Element project = parse(pomXml).getDocumentElement();
    List<Dependency> dependencies = new ArrayList<>();
    for (Element dependenciesElement : childElementsNamed(project, "dependencies")) {
      for (Element dependency : childElementsNamed(dependenciesElement, "dependency")) {
        dependencies.add(
            new Dependency(
                requiredChildText(dependency, "groupId"),
                requiredChildText(dependency, "artifactId"),
                requiredChildText(dependency, "version"),
                childText(dependency, "scope").orElse(DEFAULT_SCOPE)));
      }
    }
    return List.copyOf(dependencies);
  }

  /** Renders a POM declaring {@code dependencies} for {@code coordinate} at {@code version}. */
  public static String render(
      Coordinate coordinate, String version, List<Dependency> dependencies) {
    StringBuilder pom = new StringBuilder();
    pom.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
        .append("<!-- Generated by the ROR build from the ES ")
        .append(version)
        .append(" distribution; see ror-tools/build.gradle. -->\n")
        .append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n")
        .append("         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n")
        .append(
            "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n")
        .append("    <modelVersion>4.0.0</modelVersion>\n")
        .append("    <groupId>")
        .append(coordinate.groupId())
        .append("</groupId>\n")
        .append("    <artifactId>")
        .append(coordinate.artifactId())
        .append("</artifactId>\n")
        .append("    <version>")
        .append(version)
        .append("</version>\n")
        .append("    <packaging>jar</packaging>\n")
        .append("    <dependencies>\n");
    for (Dependency dependency : dependencies) {
      pom.append("        <dependency>\n")
          .append("            <groupId>")
          .append(dependency.groupId())
          .append("</groupId>\n")
          .append("            <artifactId>")
          .append(dependency.artifactId())
          .append("</artifactId>\n")
          .append("            <version>")
          .append(dependency.version())
          .append("</version>\n")
          .append("            <scope>")
          .append(dependency.scope())
          .append("</scope>\n")
          .append("        </dependency>\n");
    }
    return pom.append("    </dependencies>\n").append("</project>\n").toString();
  }

  private static Document parse(String xml) {
    try {
      DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
      // These POMs come off the network, so keep the parser from resolving anything they reference.
      factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
      factory.setNamespaceAware(false);
      DocumentBuilder builder = factory.newDocumentBuilder();
      return builder.parse(new InputSource(new StringReader(xml)));
    } catch (ParserConfigurationException | org.xml.sax.SAXException | java.io.IOException e) {
      throw new GradleException("Cannot parse POM: " + e.getMessage(), e);
    }
  }

  private static List<Element> childElementsNamed(Element parent, String name) {
    List<Element> elements = new ArrayList<>();
    NodeList children = parent.getChildNodes();
    for (int i = 0; i < children.getLength(); i++) {
      Node child = children.item(i);
      if (child.getNodeType() == Node.ELEMENT_NODE && name.equals(child.getNodeName())) {
        elements.add((Element) child);
      }
    }
    return elements;
  }

  private static java.util.Optional<String> childText(Element parent, String name) {
    return childElementsNamed(parent, name).stream()
        .findFirst()
        .map(e -> e.getTextContent().trim());
  }

  private static String requiredChildText(Element parent, String name) {
    return childText(parent, name)
        .orElseThrow(() -> new GradleException("POM dependency without <" + name + ">"));
  }
}
