/*
 *    This file is part of ReadonlyREST.
 *
 *    ReadonlyREST is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    ReadonlyREST is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with ReadonlyREST.  If not, see http://www.gnu.org/licenses/
 */

package tech.beshu.ror.gradle.utils;

import org.w3c.dom.Element;

import java.util.ArrayList;
import java.util.List;

/** Reads dependencies out of a published POM, and renders the POMs published to the libs store. */
public final class MavenPoms {

  public record Dependency(String groupId, String artifactId, String version, String scope) {

    public Dependency withVersion(String newVersion) {
      return new Dependency(groupId, artifactId, newVersion, scope);
    }
  }

  private static final String DEFAULT_SCOPE = "compile";

  private MavenPoms() {}

  /**
   * The dependencies a POM declares, in declaration order. Only the project's own {@code <dependencies>} is
   * read; {@code <dependencyManagement>} declares versions rather than dependencies and is ignored.
   */
  public static List<Dependency> parseDependencies(String pomXml) {
    Element project = XmlDocuments.rootOf(pomXml, "POM");
    List<Dependency> dependencies = new ArrayList<>();
    for (Element dependenciesElement : XmlDocuments.childrenNamed(project, "dependencies")) {
      for (Element dependency : XmlDocuments.childrenNamed(dependenciesElement, "dependency")) {
        dependencies.add(
            new Dependency(
                XmlDocuments.requiredChildText(dependency, "groupId"),
                XmlDocuments.requiredChildText(dependency, "artifactId"),
                XmlDocuments.requiredChildText(dependency, "version"),
                XmlDocuments.childText(dependency, "scope").orElse(DEFAULT_SCOPE)));
      }
    }
    return List.copyOf(dependencies);
  }

  public static String render(
      MavenCoordinate coordinate, String version, List<Dependency> dependencies) {
    StringBuilder pom = new StringBuilder();
    pom.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
        .append("<!-- Generated by the ROR build from the ES ")
        .append(version)
        .append(" distribution; see ror-tools/build.gradle. -->\n")
        .append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n")
        .append("         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n")
        .append(
            "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n")
        .append("    <modelVersion>4.0.0</modelVersion>\n")
        .append("    <groupId>")
        .append(coordinate.groupId())
        .append("</groupId>\n")
        .append("    <artifactId>")
        .append(coordinate.artifactId())
        .append("</artifactId>\n")
        .append("    <version>")
        .append(version)
        .append("</version>\n")
        .append("    <packaging>jar</packaging>\n")
        .append("    <dependencies>\n");
    for (Dependency dependency : dependencies) {
      pom.append("        <dependency>\n")
          .append("            <groupId>")
          .append(dependency.groupId())
          .append("</groupId>\n")
          .append("            <artifactId>")
          .append(dependency.artifactId())
          .append("</artifactId>\n")
          .append("            <version>")
          .append(dependency.version())
          .append("</version>\n")
          .append("            <scope>")
          .append(dependency.scope())
          .append("</scope>\n")
          .append("        </dependency>\n");
    }
    return pom.append("    </dependencies>\n").append("</project>\n").toString();
  }
}
