ARG ES_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

RUN  cd /usr/share/elasticsearch/config &&\
     mkdir -p /usr/share/elasticsearch/config/certs/ca

COPY generate-certs.sh /usr/share/elasticsearch/bin
COPY certs/ror-cluster-instances.yml /usr/share/elasticsearch/config/certs
COPY certs/elastic-cloud/ca.cer /usr/share/elasticsearch/config/certs

ENTRYPOINT ["/usr/share/elasticsearch/bin/generate-certs.sh"]