ARG KBN_VERSION
ARG ROR_VERSION
ARG ROR_ACTIVATION_KEY

FROM docker.elastic.co/kibana/kibana:${KBN_VERSION}

ARG KBN_VERSION
ARG ROR_VERSION
ARG ROR_ACTIVATION_KEY

COPY certs/ /usr/share/kibana/config/
COPY ror/kbn/kibana.yml /usr/share/kibana/config/kibana.yml
COPY .base/kbn/install-ror-kbn-using-api.sh /tmp/install-ror.sh

ENV ROR_ACTIVATION_KEY=$ROR_ACTIVATION_KEY
USER root

RUN /tmp/install-ror.sh
RUN chown -R kibana:kibana /usr/share/kibana/config

USER kibana