ARG KBN_VERSION
ARG ROR_VERSION
ARG ROR_ACTIVATION_KEY

FROM docker.elastic.co/kibana/kibana:${KBN_VERSION}

ARG KBN_VERSION
ARG ROR_VERSION
ARG ROR_ACTIVATION_KEY

COPY ror/kbn/kibana.yml /usr/share/kibana/config/kibana.yml
COPY certs/elastic-certificates.p12 /usr/share/kibana/config/elastic-certificates.p12
COPY .base/kbn/install-ror-kbn-using-api.sh /tmp/install-ror.sh

ENV ROR_ACTIVATION_KEY=$ROR_ACTIVATION_KEY

RUN /tmp/install-ror.sh

USER root
RUN chown -R kibana:kibana /usr/share/kibana/config
USER kibana